FROM node:16-alpine
WORKDIR /app
COPY ./package.json ./
RUN npm config set unsafe-perm true
RUN npm install  --silent

RUN chown -R node /app/node_modules

USER node

COPY . .

CMD ["npm", "run", "start"]