language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t tomdevacc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tomdevacc/react-test npm test

after_success: 
  - docker build -t tomdevacc/multi-client ./client
  - docker build -t tomdevacc/multi-nginx ./nginx
  - docker build -t tomdevacc/multi-server ./nginx
  - docker build -t tomdevacc/multi-worker ./worker
