name: Deploy MultiDocker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-complex-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/multi-complex-test npm test 

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-complex-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-complex-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-complex-server ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-complex-worker ./worker

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-complex-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-complex-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-complex-server
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-complex-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: xxx
          environment_name: xxx
          existing_bucket_name: xxx
          region: xxx
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip